name: Release Build

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: corretto
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Create Release Sign
        run: |
          echo ${{secrets.JKS_FILE}} | base64 -d  > app/TVBoxOSC.jks
      - name: Build With Gradle
        run: |
          chmod +x gradlew
          export SENTRY_AUTH_TOKEN=${{secrets.SENTRY_AUTH_TOKEN}}
          export SENTRY_PROJECT=tvbox
          ./gradlew assembleDebug --build-cache --parallel --daemon --warning-mode all \
          -Pandroid.injected.signing.store.file=TVBoxOSC.jks \
          -Pandroid.injected.signing.store.password=${{secrets.JKS_PASSWORD}} \
          -Pandroid.injected.signing.key.alias=mykey \
          -Pandroid.injected.signing.key.password=${{secrets.JKS_PASSWORD}}

      - name: generate sentry config
        run: |
          echo "defaults.project=tvbox" > sentry.properties
          echo "defaults.org=koswu" >> sentry.properties
          echo "auth.token=$SENTRY_AUTH_TOKEN" >> sentry.properties
      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          for file in `find ~ -name "*.apk" -print`; do
            mv "$file" ${{ github.workspace }}/apk/
          done
      - name: Upload App To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: debug_${{env.sha_short}}.zip
          path: ${{ github.workspace }}/apk/*